#!/usr/bin/env bash
# Write results/pax-commits.md from the pax-gfx checkout's history.
#
# The pax repo is gitignored here, so a bare hash in a result file would be
# unresolvable by anyone reading this repo on its own. This copies the hashes,
# subjects and diffstats across so a run can be tied back to the code that
# produced it without needing the other checkout to hand.

set -euo pipefail

PAX_DIR="${PAX_DIR:-components/robotman2412__pax-gfx}"
OUT="${OUT:-results/pax-commits.md}"
BASE_TAG="${BASE_TAG:-bench-baseline}"

if [ ! -d "$PAX_DIR/.git" ]; then
	echo "No pax checkout at $PAX_DIR" >&2
	exit 1
fi

range="$BASE_TAG..HEAD"
if ! git -C "$PAX_DIR" rev-parse --verify --quiet "$BASE_TAG" >/dev/null; then
	echo "No $BASE_TAG tag in $PAX_DIR; listing the last 30 commits instead" >&2
	range="-30"
fi

{
	echo "# pax-gfx commits behind these results"
	echo
	echo "Generated by \`make paxlog\`. Origin:"
	echo "\`$(git -C "$PAX_DIR" remote get-url origin 2>/dev/null || echo 'no remote')\`"
	echo
	echo "Baseline: \`$(git -C "$PAX_DIR" rev-parse "$BASE_TAG^{commit}" 2>/dev/null || echo '?')\`"
	echo " (tag \`$BASE_TAG\`)"
	echo
	echo "Current HEAD: \`$(git -C "$PAX_DIR" rev-parse HEAD)\` on"
	echo "\`$(git -C "$PAX_DIR" rev-parse --abbrev-ref HEAD)\`"
	echo

	if [ -n "$(git -C "$PAX_DIR" status --porcelain)" ]; then
		echo "**The pax checkout has uncommitted changes.** Any run measured against"
		echo "it is not reproducible from this history alone."
		echo
	fi

	if [ "$range" = "-30" ]; then
		commits=$(git -C "$PAX_DIR" log -30 --format=%H)
	else
		commits=$(git -C "$PAX_DIR" log "$range" --format=%H)
	fi

	if [ -z "$commits" ]; then
		echo "_No commits since the baseline._"
	else
		for sha in $commits; do
			echo "## \`$(git -C "$PAX_DIR" rev-parse --short=12 "$sha")\` $(git -C "$PAX_DIR" log -1 --format=%s "$sha")"
			echo
			echo "$(git -C "$PAX_DIR" log -1 --format='%an, %ad' --date=short "$sha")"
			echo
			echo '```'
			git -C "$PAX_DIR" show --stat --format="" "$sha"
			echo '```'
			echo
		done
	fi
} >"$OUT"

echo "  wrote $OUT"
